version: '3'
services:
  php-fpm:
    image: php:8.2-fpm
    volumes:
      - ./meu-projeto-php:/var/www/html
  nginx:
    image: nginx:latest
    volumes:
      - ./meu-projeto-php:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
